### ISSUE TITLE
Device ID and Device EUI

### ISSUE THREAD

**Issue by sBooz** [RobPo/PaperiNode#1]
Hi
Thanks for the great work. In the description for TTN Network registration is written: "Please add the Device ID and Device EUI in the fields as provided with LoraPaper and select 'Register'." Where can I find Device EUI? Thanks and best regards,  Ruedi

**Comment by RobPo** [comment]
Hi @sBooz , I just went through the registration process and updated the documentation: https://github.com/RobPo/PaperiNode/tree/master/examples/06_WeatherForecast
Please check if this is working; if not please let me know where things don't run. Thanks!

**Comment by sBooz** [comment]
Thank you very much. I like the PaperiNode very much, extremly great work! 
sBooz http://www.zuerich.technology/

**Comment by RobPo** [comment]
Thanks! If there are still any issues pls let me know I will try to further document so that others can benefit too.
