### ISSUE TITLE
Hardware design files missing

### ISSUE THREAD

**Issue by Kater--S** [RobPo/PaperiNode#2]
In order to further develop for the hardware, it would be helpful to have at least a schematic so we can understand the device's mode of operation.
Unfortunately all hardware design files are missing on the Tindie page as well as here in the repo.

**Comment by sBooz** [comment]
I found some information here: https://www.hackster.io/news/this-incredible-battery-free-lora-epaper-display-is-flexing-on-your-pcb-construction-techniques-e855909f135a

**Comment by RobPo** [comment]
The schematic can be found here: https://github.com/RobPo/PaperiNode/tree/master/schematics The de-activated components are optional (e.g. battery CR2032) or soldered by hand (e.g. PV cells).
