### ISSUE TITLE
Create smaller preview image in `readme.md`

### ISSUE THREAD

**Issue by abetusk** [RobPo/PaperiNode#4]
The preview image (as of this writing, [this image](https://user-images.githubusercontent.com/21104467/85378463-e13fb200-b53a-11ea-95d8-0eedb5c36a9c.png)) is upwards of a 8Mb `PNG` file which takes a long time to load and is needlessly large. Reducing the size would lead to faster load times without a loss of viewing quality.

I would also recommend putting the preview image into the repository and providing a relative link in the `readme.md` to make the repo as self contained as possible.

I've attached a reduced `PNG` image that is 891x501 and is only 629Kb (a 10x+ reduction in space) and a `JPG` 891x501 that is 118Kb in size (a 70x+ reduction in space) either of which would probably be good enough to be put into the `readme.md`.

![paperinode-preview](https://user-images.githubusercontent.com/1406122/96310733-f3f06200-0fd5-11eb-840a-b14d3baa646a.png)

![paperinode-preview](https://user-images.githubusercontent.com/1406122/96310953-63665180-0fd6-11eb-8dae-6c7fcc37e019.jpg)

**Comment by RobPo** [comment]
Completely agreed and thanks for proposed size reduction. Just implemented the smaller pic!
